### ISSUE TITLE
Arena frames error messages

### ISSUE THREAD

**Issue by Caerban** [Gennoken/GennUI#2]
<img width="357" alt="Snímek obrazovky 2021-12-03 v 16 38 47" src="https://user-images.githubusercontent.com/95495410/144642917-e2b63687-8d6b-4cb3-b752-49cb70ab72d0.png">

**Comment by Gennoken** [comment]
You need to be more specific.
I need the full error, and what does arena frames do in ICC ?
And is this with only GennUI+ElvUI loaded ??

Also, that's not how GennUI chat looks, are you sure you are not using something else ?
