### ISSUE TITLE
Extra textures and font from Skullflower UI

### ISSUE THREAD

**Issue by DenzahLT** [Gennoken/GennUI#23]
Hello,

Love your work ;)

Is there a way to add extra textures from https://www.wowinterface.com/downloads/info24487-SkullflowersUIContinuedAgain.htm
![Untitled](https://user-images.githubusercontent.com/32670175/186214162-13908a16-65cd-47df-92b3-1bcc445881bd.png)
l
same for the font Expressway

Also can we have the icon inside the tooltip instead of outside ?

**Comment by Gennoken** [comment]
- For Expressway, it comes already with ElvUI, i think you can find it in any dropdown font manu setting in your Addons.
- For the textures, my texture GennUI is based already of Skullflower, i believe based on the "Light" one, if you want more, you'll need to add them manually to the /media/textures in GennUI, and you'll need to do so after every update.
OR load Skullflower UI and don't install it, you should see it's textures in any dropbdown statusbars menu in your addons.
- For the Icon inside the tooltip it'll be done next update.

**Comment by DenzahLT** [comment]
ok thank you ;)
