### ISSUE TITLE
Issues with UI for WotLK

### ISSUE THREAD

**Issue by ShleppyGaming** [Gennoken/GennUI#26]
15x ...vUI\Libraries\Core\Ace\AceEvent-3.0\AceEvent-3.0-4.lua:33: Attempt to register unknown event "CURSOR_UPDATE"
[string "=[C]"]: in function `RegisterEvent'
[string "@ElvUI\Libraries\Core\Ace\AceEvent-3.0\AceEvent-3.0-4.lua"]:33: in function `OnUsed'
[string "@AtlasLootClassic\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:142: in function `RegisterEvent'
[string "@GatherMate2\Collector.lua"]:77: in function `RegisterGatherEvents'
[string "@GatherMate2\Collector.lua"]:66: in function <GatherMate2\Collector.lua:65>
[string "=[C]"]: ?
[string "@Details\Libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:70: in function <...ceDetails\Libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Details\Libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:527: in function `EnableAddon'
[string "@Details\Libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:540: in function `EnableAddon'
[string "@Details\Libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:630: in function <...ceDetails\Libs\AceAddon-3.0\AceAddon-3.0.lua:615>

14438x GTFO\GTFO-4.66.6.lua:1581: attempt to call global 'GetSpecialization' (a nil value)
[string "@GTFO\GTFO-4.66.6.lua"]:1581: in function `GTFO_CheckTankMode'
[string "@GTFO\GTFO-4.66.6.lua"]:269: in function `GTFO_OnEvent'
[string "*:OnEvent"]:1: in function <[string "*:OnEvent"]:1>

Locals:
x = "Death Knight"
class = "DEATHKNIGHT"
(*temporary) = nil
(*temporary) = "attempt to call global 'GetSpecialization' (a nil value)"

**Comment by Gennoken** [comment]
I don't see where this is GennUI related.
Before reporting any bugs you should start WoW with only ElvUI and GennUI loaded. Here i can see you have Details, GTFO, GatherMate2 and maybe more.
