### ISSUE TITLE
Lua Error installing plugin

### ISSUE THREAD

**Issue by Spirezzz** [Gennoken/GennUI#27]
Hi, I am getting this error installing your plugin:

Message: Interface\AddOns\ElvUI_GennUI\core\unitframes.lua:481: attempt to index field 'raid' (a nil value)
Time: Wed Sep 14 19:35:16 2022
Count: 1
Stack: Interface\AddOns\ElvUI_GennUI\core\unitframes.lua:481: attempt to index field 'raid' (a nil value)
[string "=[C]"]: ?
[string "@Interface\AddOns\ElvUI_GennUI\core\unitframes.lua"]:481: in function `SetupUnitframes'
[string "@Interface\AddOns\ElvUI_GennUI\core.lua"]:61: in function `SetupLayout'
[string "@Interface\AddOns\ElvUI_GennUI\init.lua"]:76: in function <Interface\AddOns\ElvUI_GennUI\init.lua:76>

Locals:

**Comment by Gennoken** [comment]
You need to be more specific
Retail or Classic ?
Which version of GennUI and ElvUI ?
Did u try fresh install with only GennUI and ElvUI loaded ?

**Comment by Spirezzz** [comment]
Retail
Elvui 12.87 and gennui 2.71
yes, i tried using only those 2 addons and even reinstaling the game

I asked on the elvui discord and someone sayed it is due to the new options for raid 1 2 3.

**Comment by Gennoken** [comment]
Will look into it as soon as I get home

**Comment by Gennoken** [comment]
Fixed in 2.72
