### ISSUE TITLE
pet and stance bar missing

### ISSUE THREAD

**Issue by erwinversluis2** [Gennoken/GennUI#36]
after install and going through the initial setup the pet and stance bar are not shown.

i can enable it with the default elvui set, by picking he bar and choose restore bar. After that i move the bar to a good spot.  (After the restore option the stance bar is located on top of action bar 1, while pet bar appear on a normal useable location)

Is there any methods to have those automatically enabled ? because on each character i seems to have to run the /gnui install option again the fix the layour, and each item those 2 bars are hidden.

In the initial phase on step "setup layout" there is where the stance & pet bar will vanish if it had been re-enabled on another character.

**Comment by Gennoken** [comment]
Retail or Wrath or Classic ?

**Comment by Gennoken** [comment]
I've just double checked both retail and classic, everything's fine.
Keep in mind that in GennUI both pet bar and stance bar are hidden unless you mouse over them, you can toggle all ankers in ElvUI to see where they are, or see my "All Movers" Screenshot.

If you like them visible just do so in ElvUI settings.

Also if you make a lot of changes to GennUI and would like to keep them after every update, just click "Skip Process" when installer pops after you update GennUI

**Comment by erwinversluis2** [comment]
I didnt know where de stance button were located. But they are (if i use the option /moveui) on top of an action bar just below the raid frames. After restore i move the buttons just above the raid 
Have still to configure couple of characters to use the new interface where i need to use the /gnui option to get the gui fixed. Will check if i hover over the location if it appears.
Op vr., okt. 28, 2022 om 01:07, Gennoken ***@***.***> schreef:
	I've just double checked both retail and classic, everything's fine.
 Keep in mind that in GennUI both pet bar and stance bar are hidden unless you mouse over them, you can toggle all ankers in ElvUI to see where they are, or see my "All Movers" Screenshot. 

	If you like them visible just do so in ElvUI settings. 

	Also if you make a loot of changes to GennUI and would like to keep them after every update, just click "Skip Process" when installer pops after you update GennUI
