### ISSUE TITLE
LUA errors

### ISSUE THREAD

**Issue by Naehars** [Gennoken/GennUI#40]
I receive a tooltipicon LUA error from ElvUI and GennUI, might be that the new patch broke something?

**Comment by Naehars** [comment]
Message: Interface/FrameXML/EditModeUtil.lua:27: attempt to perform arithmetic on local 'offsetX' (a nil value)
Time: Mon Nov 28 14:58:00 2022
Count: 1
Stack: Interface/FrameXML/EditModeUtil.lua:27: attempt to perform arithmetic on local 'offsetX' (a nil value)
[string "=[C]"]: ?
[string "@Interface/FrameXML/EditModeUtil.lua"]:27: in function `GetRightActionBarWidth'
[string "@Interface/FrameXML/ContainerFrame.lua"]:1141: in function <Interface/FrameXML/ContainerFrame.lua:1140>
[string "@Interface/FrameXML/ContainerFrame.lua"]:1145: in function <Interface/FrameXML/ContainerFrame.lua:1144>
[string "@Interface/FrameXML/ContainerFrame.lua"]:1197: in function `UpdateContainerFrameAnchors'
[string "@Interface/FrameXML/ContainerFrame.lua"]:1134: in function `ContainerFrame_GenerateFrame'
[string "@Interface/FrameXML/ContainerFrame.lua"]:138: in function `ToggleBag_Individual'
[string "@Interface/FrameXML/ContainerFrame.lua"]:156: in function <Interface/FrameXML/ContainerFrame.lua:148>
[string "=[C]"]: in function `ToggleBag'
[string "@Interface/FrameXML/ContainerFrame.lua"]:107: in function `ToggleBackpack_Individual'
[string "@Interface/FrameXML/ContainerFrame.lua"]:119: in function <Interface/FrameXML/ContainerFrame.lua:111>
[string "=[C]"]: in function `ToggleBackpack'
[string "@Interface/FrameXML/ContainerFrame.lua"]:290: in function `OpenBackpack'
[string "@Interface/FrameXML/ContainerFrame.lua"]:1826: in function <Interface/FrameXML/ContainerFrame.lua:1825>
[string "@Interface/FrameXML/ContainerFrame.lua"]:1888: in function <Interface/FrameXML/ContainerFrame.lua:1859>
[string "=[C]"]: in function `ToggleAllBags'
[string "OPENALLBAGS"]:1: in function <[string "OPENALLBAGS"]:1>

Locals:

**Comment by Naehars** [comment]
Message: ...nterface/AddOns/ElvUI_GennUI/modules/tooltipicon.lua:436: attempt to index upvalue 'options' (a nil value)
Time: Mon Nov 28 14:33:21 2022
Count: 4
Stack: ...nterface/AddOns/ElvUI_GennUI/modules/tooltipicon.lua:436: attempt to index upvalue 'options' (a nil value)
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI_GennUI/modules/tooltipicon.lua"]:436: in function <...nterface/AddOns/ElvUI_GennUI/modules/tooltipicon.lua:434>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `securecallfunction'
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:60: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:55>
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:80: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:76>
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:116: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:106>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:141: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:134>
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:282: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:240>
[string "=[C]"]: in function `securecallfunction'
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:237: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:236>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/ElvUI/Core/Modules/DataTexts/Durability.lua"]:52: in function `eventFunc'
[string "@Interface/AddOns/ElvUI/Core/Modules/DataTexts/DataTexts.lua"]:348: in function `AssignPanelToDataText'
[string "@Interface/AddOns/ElvUI/Core/Modules/DataTexts/DataTexts.lua"]:488: in function `UpdatePanelInfo'
[string "@Interface/AddOns/ElvUI/Core/Modules/DataTexts/DataTexts.lua"]:506: in function `LoadDataTexts'
[string "@Interface/AddOns/ElvUI/Core/Modules/DataTexts/DataTexts.lua"]:749: in function `?'
[string "@Interface/AddOns/ElvUI_Libraries/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:117: in function <...ies/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua:117>
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI_Libraries/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:27: in function <...ies/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua:23>
[string "@Interface/AddOns/ElvUI_Libraries/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:62: in function `Fire'
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <...UI_Libraries/Core/Ace3/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals:

**Comment by Naehars** [comment]
Message: Interface/FrameXML/EditModeSystemTemplates.lua:631: attempt to perform arithmetic on local 'offsetY' (a nil value)
Time: Mon Nov 28 14:43:56 2022
Count: 1
Stack: Interface/FrameXML/EditModeSystemTemplates.lua:631: attempt to perform arithmetic on local 'offsetY' (a nil value)
[string "=[C]"]: ?
[string "@Interface/FrameXML/EditModeSystemTemplates.lua"]:631: in function `GetBottomAnchoredHeight'
[string "@Interface/FrameXML/EditModeUtil.lua"]:39: in function `GetBottomActionBarHeight'
[string "@Interface/FrameXML/UIParent.lua"]:3083: in function `UIParentManageFramePositions'
[string "@Interface/FrameXML/UIParent.lua"]:2570: in function <Interface/FrameXML/UIParent.lua:2557>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface/FrameXML/UIParent.lua"]:3113: in function <Interface/FrameXML/UIParent.lua:3111>
[string "=[C]"]: in function `UIParent_ManageFramePositions'
[string "@Interface/FrameXML/EditModeManager.lua"]:640: in function `UpdateBottomActionBarPositions'
[string "@Interface/FrameXML/EditModeManager.lua"]:561: in function `UpdateActionBarPositions'
[string "@Interface/FrameXML/EditModeManager.lua"]:890: in function `UpdateLayoutInfo'
[string "@Interface/FrameXML/EditModeManager.lua"]:239: in function <Interface/FrameXML/EditModeManager.lua:231>

Locals:

**Comment by Naehars** [comment]
Message: Interface/FrameXML/EditModeSystemTemplates.lua:631: attempt to perform arithmetic on local 'offsetY' (a nil value)
Time: Mon Nov 28 14:43:56 2022
Count: 1
Stack: Interface/FrameXML/EditModeSystemTemplates.lua:631: attempt to perform arithmetic on local 'offsetY' (a nil value)
[string "=[C]"]: ?
[string "@Interface/FrameXML/EditModeSystemTemplates.lua"]:631: in function `GetBottomAnchoredHeight'
[string "@Interface/FrameXML/EditModeUtil.lua"]:39: in function `GetBottomActionBarHeight'
[string "@Interface/FrameXML/UIParent.lua"]:3083: in function `UIParentManageFramePositions'
[string "@Interface/FrameXML/UIParent.lua"]:2570: in function <Interface/FrameXML/UIParent.lua:2557>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface/FrameXML/UIParent.lua"]:3113: in function <Interface/FrameXML/UIParent.lua:3111>
[string "=[C]"]: in function `UIParent_ManageFramePositions'
[string "@Interface/FrameXML/EditModeManager.lua"]:604: in function `UpdateRightActionBarPositions'
[string "@Interface/FrameXML/EditModeManager.lua"]:562: in function `UpdateActionBarPositions'
[string "@Interface/FrameXML/EditModeManager.lua"]:890: in function `UpdateLayoutInfo'
[string "@Interface/FrameXML/EditModeManager.lua"]:239: in function <Interface/FrameXML/EditModeManager.lua:231>

Locals:

**Comment by Naehars** [comment]
Editmode LUA errors don't happen when I disable ElvUI & GennUI

**Comment by Gennoken** [comment]
looking into it

**Comment by Gennoken** [comment]
aparently ElvUI related and got fixed.
