### ISSUE TITLE
Raid Frames Moving

### ISSUE THREAD

**Issue by cakesicle** [Gennoken/GennUI#42]
Hello,

Having issues with raid frames anchoring. When moving to heroic -> mythic level difficulty or vice-a-versa, the frames shift higher or lower, respectively. I've tried disabling Raid 2 and Raid 3 or messing with the settings on visibility, but seems to still do it. See below for examples.

![ign](https://user-images.githubusercontent.com/122766085/212595357-5388487f-e40a-4c32-9531-1f6889f91c0d.png)
![outsz](https://user-images.githubusercontent.com/122766085/212595363-af969f1a-104b-436f-ae6e-707d8a299eea.png)

Tried reaching out to the ElvUI community but got no response either.

**Comment by Gennoken** [comment]
Hello,
I can see you edited a bit my raid frames, so this is not  a bug, it's more like a configuration issue
first reset the visibility of your raid1/2/3 to their default values
then configure your raid1/2/3 frames as you like
then enable raid1/2/3 anchors and align them correctly on top of each other from the top.

**Comment by cakesicle** [comment]
Hi,

What were the default visibility values, again? I'd like to try this out as
I have raid tonight.

Thanks!

*Fonny Wu*
(626) 329-8153

**Comment by Gennoken** [comment]
**Retail**
Party: `[@raid6,exists][nogroup] hide;show`
Raid 1: `[@raid6,noexists][@raid21,exists] hide;show`
Raid 2: `[@raid21,noexists][@raid31,exists] hide;show`
Raid 3: `[@raid31,noexists] hide;show`

**Classic**
Party: `[@raid6,exists][nogroup] hide;show`
Raid 1: `[@raid6,noexists][@raid11,exists] hide;show`
Raid 2: `[@raid11,noexists][@raid26,exists] hide;show`
Raid 3: `[@raid26,noexists] hide;show`

**Comment by cakesicle** [comment]
Hi,

So, I've tried resetting to default and also made sure that the
visibility notes match per your previous email. However, it seems that my
Raid 2 anchors are still automatically shifting down when I enter mythic
raid when there's 20+ in the group. It will shift back into its original
anchor when I go outside, though.

Any other ideas to resolve this?

Thanks,

**Comment by Gennoken** [comment]
Okey,
To really pin point the problem.
1. Disable ALL addons execpt ElvUI and GennUI
2. Make a new blank profile and run GennUI setup
3. Do not change ANYTHING and go test in raid. (no need to play with a profile you are nor confortable with, just zone in a bit before raid and test, you can switch to your profile and enable addons before pulls)

**Comment by cakesicle** [comment]
Hello,

Just started testing this. All my add-ons and WA are turned off. I did a
new profile as well and reset everything per GennUI setup; no
modifications were made.

Seems like the frames are growing down/shifting down now and cutting out
G5+. There was a group size of 18.

Let me know if there's something with the anchors??

Thanks!
