### ISSUE TITLE
Error in fresh install

### ISSUE THREAD

**Issue by Elschnuppero** [Gennoken/GennUI#6]
Hi there, 

i get the following error on a fresh install:

`
Message: Interface\AddOns\ElvUI_GennUI\core\nameplates.lua:278: attempt to index field 'nameplate' (a nil value)
Time: Sat Jan 22 17:38:46 2022
Count: 1
Stack: Interface\AddOns\ElvUI_GennUI\core\nameplates.lua:278: attempt to index field 'nameplate' (a nil value)
[string "=[C]"]: ?
[string "@Interface\AddOns\ElvUI_GennUI\core\nameplates.lua"]:278: in function `SetupNameplates'
[string "@Interface\AddOns\ElvUI_GennUI\core.lua"]:59: in function `SetupLayout'
[string "@Interface\AddOns\ElvUI_GennUI\init.lua"]:76: in function <Interface\AddOns\ElvUI_GennUI\init.lua:76>

Locals: 
`
Thank you :)

**Comment by Repooc** [comment]
all references to `E.global["nameplate"]` should be `E.global["nameplates"]` now

**Comment by Gennoken** [comment]
> all references to `E.global["nameplate"]` should be `E.global["nameplates"]` now

Hi @Repooc, I don't have game time active ATM, but a low level character should be okay to fix things on Retail, however in classic did ElvUI got updated with these changes too or is it only for retail.. Been away for a while now due to work so i'm not up to date with ElvUI dev.

**Comment by Azilroka** [comment]
All versions

**Comment by Gennoken** [comment]
Thx, so one fix should rule them all
Fixed in 2.65
