### ISSUE TITLE
about elvui Unit Prefix Style

### ISSUE THREAD

**Issue by LiBoHan95** [Gennoken/GennUI#64]
When I changed the Unit Prefix Style from k, m, p to 千, 万, 百万 in ElvUI, it didn't display correctly in the blood bar. Do I need to make any unique settings?

**Comment by LiBoHan95** [comment]
I really like your style of setting up this elvui, but in China, I'd prefer to see 千, 万, 百万

**Comment by Gennoken** [comment]
What do you mean by Blood Bar

**Comment by LiBoHan95** [comment]
Health value on the individual unit frame

**Comment by Gennoken** [comment]
yeah yeah i know but i'm not chineese i have no clue xD
besides, my plugin is an ElvUI profile, it has nothing to do with these values.
Have u tried to deplay what you need with only ElvUI loaded, so that we can safely say it's GennUI related ?

**Comment by LiBoHan95** [comment]
Thank you so much for your enthusiastic reply XD

I know it's probably not related to GennUI, but if I load Elvui alone, setting the Unit Prefix Style works, but once GennUI is loaded, setting the Unit Prefix Style doesn't work....

I don't know what to do next to troubleshoot the problem, can you point me in the right direction?

**Comment by LiBoHan95** [comment]
I may have found the problem.

Under the `E:ShortValue` method in `math.lua`, is this the method that is causing the Unit Prefix Style error to display?

Is it because this method overrides the `E:ShortValue` method in `Core/General/Math.lua` under Elvui?

I don't know much about Lua runtime logic, I don't know how to modify and test it, maybe the description is wrong, please help me...

Thanks!

**Comment by Gennoken** [comment]
Found the problem, witch is 2 steps problem
1. E:ShortValue in my math.lua overrides the one from ElvUI, i can fix this in the next release.
2. The second cause is the font i'm using does not support Chinese, wich can't be changed.

What u can do make it work
1. In the toc file corresponding to your game version, for example ElvUI_GennUI.toc for retail, you delete the whole line "math.lua"
you do this once, cuz next update i'll have it fixed
2. Sadly, you have to manually change the font of every text you want it to display Chinese, those font that start with AR intheir names in the font list, this applies to heath and mana to all unitframes, you do this once and after every update just hit skip install button to keep your settings

Sorry for this until i figure out a better way

**Comment by LiBoHan95** [comment]
Very hurry your help, this is a great UI!
