### ISSUE TITLE
classic era tooltipicon.lua

### ISSUE THREAD

**Issue by MWojtan-TPA** [Gennoken/GennUI#65]
2982x ElvUI_GennUI/modules/tooltipicon.lua:525: attempt to call upvalue 'GetSpellTexture' (a nil value)
[string "@ElvUI_GennUI/modules/tooltipicon.lua"]:525: in function <ElvUI_GennUI/modules/tooltipicon.lua:514>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `SetAction'
[string "@ElvUI_Libraries/Core/LibActionButton-1.0/LibActionButton-1.0.lua"]:2689: in function `SetTooltip'
[string "@ElvUI_Libraries/Core/LibActionButton-1.0/LibActionButton-1.0.lua"]:2393: in function <...ies/Core/LibActionButton-1.0/LibActionButton-1.0.lua:2385>
[string "@ElvUI_Libraries/Core/LibActionButton-1.0/LibActionButton-1.0.lua"]:1254: in function <...ies/Core/LibActionButton-1.0/LibActionButton-1.0.lua:1252>
[string "=(tail call)"]: ?
[string "=[C]"]: ?

Locals:
frame = GameTooltip {
 0 = <userdata>
 GetBackdropColor = <function> defined @Blizzard_SharedXML/SharedTooltipTemplates.lua:326
 SetHyperlink = <function> defined =[C]:-1
 SetGuildBankItem = <function> defined =[C]:-1
 hasMoney = 1
 SetBackdropBorderColor = <function> defined @Blizzard_SharedXML/SharedTooltipTemplates.lua:330
 Hide = <function> defined =[C]:-1
 SetCraftItem = <function> defined =[C]:-1
 BottomOverlay = Texture {
 }
 TopOverlay = Texture {
 }
 GetBackdropBorderColor = <function> defined @Blizzard_SharedXML/SharedTooltipTemplates.lua:334
 default = 1
 SetUnitDebuff = <function> defined =[C]:-1
 SetItemByID = <function> defined =[C]:-1
 SetLootItem = <function> defined =[C]:-1
 SetQuestItem = <function> defined =[C]:-1
 StatusBar = GameTooltipStatusBar {
 }
 SetBorderBlendMode = <function> defined @Blizzard_SharedXML/SharedTooltipTemplates.lua:338
 SetTrainerService = <function> defined =[C]:-1
 numMoneyFrames = 2
 SetToyByItemID = <function> defined =[C]:-1
 SetCurrencyToken = <function> defined =[C]:-1
 SetInboxItem = <function> defined =[C]:-1
 layoutType = "TooltipDefaultLayout"
 shoppingTooltips = <table> {
 }
 GetTooltipData = <function> defined @ElvUI/Core/General/API.lua:879
 SetMerchantItem = <function> defined =[C]:-1
 SetQuestLogItem = <function> defined =[C]:-1
 SetMerchantCostItem = <function> defined =[C]:-1
 SetTradeTargetItem = <function> defined =[C]:-1
 SetTradePlayerItem = <function> defined =[C]:-1
 SetTradeSkillItem = <function> defined =[C]:-1
 SetSendMailItem = <function> defined =[C]:-1
 SetCraftSpell = <function> defined =[C]:-1
 updateTooltip = 0.200000
 SetInventoryItem = <function> defined =[C]:-1
 SetUnitBuff = <function> defined =[C]:-1
 NineSlice = Frame {
 }
 TooltipBackdropOnLoad = <function> defined @Blizzard_SharedXML/SharedTooltipTemplates.lua:307
 SetUnitAura = <function> defined =[C]:-1
 SetBuybackItem = <function> defined =[C]:-1
 SetAuctionSellItem = <function> defined =[C]:-1
 SetBagItem = <function> defined =[C]:-1
 needsReset = true
 SetAction = <function> defined =[C]:-1
 SetBackdropColor = <function> defined @Blizzard_SharedXML/SharedTooltipTemplates.lua:322
 SetLootRollItem = <function> defined =[C]:-1
 SetAuctionItem = <function> defined =[C]:-1
}
name = "Create Healthstone (Major)"
spellID = 11730
data = <table> {
 parent = GameTooltip {
 }
 defaultlocation = <table> {
 }
}
(*temporary) = nil
(*temporary) = 11730
(*temporary) = "attempt to call upvalue 'GetSpellTexture' (a nil value)"
options = <table> {
 achievement = true
 spell = true
 item = true
 toy = true
 token = true
 equipmentset = true
}
IconDataTable = <table> {
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
  = <table> {
 }
}
GetDisplayedSpell = <function> defined @ElvUI_GennUI/modules/tooltipicon.lua:67
GetSpellTexture = nil
DisplayIconDispatch = <function> defined @ElvUI_GennUI/modules/tooltipicon.lua:138

**Comment by MWojtan-TPA** [comment]
tousands of errors while moving mouse across bars in era

**Comment by Gennoken** [comment]
fixed in 2.90, should be out tomorrow ahead of retail S1
