### ISSUE TITLE
LUA ERROR with ElvUI v. 12.61

### ISSUE THREAD

**Issue by Speckbarbie** [Gennoken/GennUI#7]
After updating ElvUI to 12.61 i'm get this errors:

Message: Interface\AddOns\ElvUI_GennUI\core\nameplates.lua:278: attempt to index field 'nameplate' (a nil value)
Time: Sun Jan 23 18:59:25 2022
Count: 1
Stack: Interface\AddOns\ElvUI_GennUI\core\nameplates.lua:278: attempt to index field 'nameplate' (a nil value)
[string "=[C]"]: ?
[string "@Interface\AddOns\ElvUI_GennUI\core\nameplates.lua"]:278: in function `SetupNameplates'
[string "@Interface\AddOns\ElvUI_GennUI\core.lua"]:59: in function `SetupLayout'
[string "@Interface\AddOns\ElvUI_GennUI\init.lua"]:76: in function <Interface\AddOns\ElvUI_GennUI\init.lua:76>

and: 

Message: Interface\AddOns\ElvUI_GennUI\core\theme.lua:33: attempt to index field 'customTexts' (a nil value)
Time: Sun Jan 23 18:23:59 2022
Count: 1
Stack: Interface\AddOns\ElvUI_GennUI\core\theme.lua:33: attempt to index field 'customTexts' (a nil value)
[string "=[C]"]: ?
[string "@Interface\AddOns\ElvUI_GennUI\core\theme.lua"]:33: in function `SetupTheme'
[string "@Interface\AddOns\ElvUI_GennUI\init.lua"]:87: in function <Interface\AddOns\ElvUI_GennUI\init.lua:87>

**Comment by Gennoken** [comment]
Fixed in 2.65
